import test from 'node:test';
import assert from 'node:assert/strict';
import {fakeDB} from './fake-store.js';
process.env.NODE_ENV='test';process.env.ENABLE_FIREBASE_ADMIN='true';process.env.FIREBASE_PROJECT_ID='fixture-project';
const {setTestServices,lockDraft,commitDraft,getDraft,unlockDraft}=await import('../server/store.js');
const {app}=await import('../server/index.js');
const {blankPreferences}=await import('../server/domain.js');
const {usageUserKey}=await import('../server/usage.js');
const id='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa';
const fixture=fakeDB({[`trips/${id}`]:{id,owner:'alice',createdAt:'2026-10-08',preferences:{},plan:{},reviewStatus:'Pending',approvedExplanation:null},[`privateReviews/${id}`]:{owner:'alice',status:'Pending',draft:'PRIVATE EXPLANATION'}});
setTestServices({db:fixture.db,auth:{verifyIdToken:async token=>{if(token==='alice'||token==='bob')return {uid:token,auth_time:Date.now()/1000};if(token==='reviewer')return {uid:'reviewer',trusttripReviewer:true};throw Error('bad token');}}});
const server=app.listen(0,'127.0.0.1');await new Promise(resolve=>server.once('listening',resolve));const origin=`http://127.0.0.1:${server.address().port}`;
test.after(()=>server.close());
async function req(url,token,method='GET',body,headers={}){return fetch(origin+url,{method,headers:{...(token?{Authorization:'Bearer '+token}:{}),'Content-Type':'application/json',...headers},...(body?{body:JSON.stringify(body)}:{})});}
test('private routes reject missing and invalid authentication',async()=>{assert.equal((await req('/api/trips')).status,401);assert.equal((await req('/api/trips','invalid')).status,401);});
test('a second user cannot read another user trip',async()=>{assert.equal((await req('/api/trips/'+id,'bob')).status,404);assert.equal((await req('/api/trips/'+id,'alice')).status,200);});
test('traveller cannot access private review endpoint or approve',async()=>{assert.equal((await req('/api/reviews','alice')).status,403);assert.equal((await req('/api/reviews/'+id,'alice','POST',{decision:'Approved',text:'forged',humanConfirmed:true})).status,403);});
test('traveller list contains no private draft',async()=>{const r=await req('/api/trips','alice'),text=await r.text();assert.equal(text.includes('PRIVATE EXPLANATION'),false);assert.equal(JSON.parse(text).trips[0].approvedExplanation,null);});
test('cross-origin writes rejected before mutation',async()=>assert.equal((await req('/api/draft','alice','PUT',{}, {Origin:'https://evil.example'})).status,403));
test('generation requires explicit fictional evaluation consent',async()=>assert.equal((await req('/api/trips','alice','POST',{version:0,evaluationOnly:false})).status,422));
test('competing chat/manual edits conflict; committed draft persists in store',async()=>{const {token}=await lockDraft('alice',0);await assert.rejects(()=>lockDraft('alice',0),/in progress/);await commitDraft('alice',token,{preferences:{...blankPreferences(),origin:'Jaipur'}});assert.equal((await getDraft('alice')).preferences.origin,'Jaipur');await assert.rejects(()=>lockDraft('alice',0),/another tab/);});
test('stale worker cannot commit or clear a successor lease',async()=>{const {token}=await lockDraft('alice',1);const d=fixture.data.get('users/alice/state/draft');d.lease={token:'successor',until:Date.now()+90000};await assert.rejects(()=>commitDraft('alice',token,{}),/expired/);await unlockDraft('alice',token);assert.equal(fixture.data.get('users/alice/state/draft').lease.token,'successor');});
test('owner deletion needs explicit confirmation and rejects active work',async()=>{assert.equal((await req('/api/account','alice','DELETE',{confirm:'wrong'})).status,422);assert.equal((await req('/api/account','alice','DELETE',{confirm:'DELETE'})).status,409);});
test('service webhook rejects unauthenticated calls',async()=>assert.equal((await req('/api/automation/run',null,'POST',{tripId:id})).status,401));

test('chat returns an honest unconfigured error without saving fabricated history',async()=>{delete process.env.GEMINI_API_KEY;delete process.env.GEMINI_MODEL;fixture.data.set('users/bob/state/draft',{preferences:blankPreferences(),messages:[],version:0,lease:null});const r=await req('/api/chat','bob','POST',{message:'A trip to Shimla',version:0});assert.equal(r.status,503);assert.equal(fixture.data.get('users/bob/state/draft').messages.length,0);assert.equal(fixture.data.get('users/bob/state/draft').version,0);});
test('generation rejects confirmation values differing from saved preferences',async()=>{const saved={...blankPreferences(),origin:'Delhi'};fixture.data.set('users/bob/state/draft',{preferences:saved,version:3,lease:null});const r=await req('/api/trips','bob','POST',{version:3,evaluationOnly:true,reviewed:true,confirmedPreferences:{...saved,origin:'Jaipur'}});assert.equal(r.status,409);assert.match((await r.json()).error,/preferences you reviewed/);assert.equal(fixture.data.get('users/bob/state/draft').preferences.origin,'Delhi');});
test('generation rejects stale review version and missing explicit review',async()=>{const saved={...blankPreferences(),origin:'Delhi'};assert.equal((await req('/api/trips','bob','POST',{version:2,evaluationOnly:true,reviewed:true,confirmedPreferences:saved})).status,409);assert.equal((await req('/api/trips','bob','POST',{version:3,evaluationOnly:true,confirmedPreferences:saved})).status,422);});
test('conversation history persists through optional summary edits',async()=>{fixture.data.set('users/bob/state/draft',{preferences:blankPreferences(),version:4,lease:null,messages:[{role:'user',text:'Saved trip question'}]});assert.equal((await (await req('/api/draft','bob')).json()).messages[0].text,'Saved trip question');const r=await req('/api/draft','bob','PUT',{version:4,preferences:{...blankPreferences(),origin:'Jaipur'}});assert.equal(r.status,200);assert.equal(fixture.data.get('users/bob/state/draft').messages[0].text,'Saved trip question');});

test('chat rejects caller-supplied roles and identity fields',async()=>{const r=await req('/api/chat','bob','POST',{message:'hello',version:5,role:'system',owner:'alice'});assert.equal(r.status,422);});
test('real chat integration calls provider and commits only schema-valid output (provider double)',async()=>{const originalFetch=globalThis.fetch;const saved={...blankPreferences(),origin:'Jaipur'};fixture.data.set('users/bob/state/draft',{preferences:saved,messages:[{role:'user',text:'Earlier question'},{role:'assistant',text:'Earlier response'}],version:6,lease:null});process.env.GEMINI_API_KEY='test-only';process.env.GEMINI_MODEL='test-only';let providerBody;globalThis.fetch=async(url,options)=>{if(String(url).startsWith('https://generativelanguage.googleapis.com/')){providerBody=JSON.parse(options.body);return new Response(JSON.stringify({candidates:[{content:{parts:[{text:JSON.stringify({reply:'What travel dates would you like?',preferences:{...saved,destination:'Shimla'}})}]}}]}),{status:200});}return originalFetch(url,options);};try{const r=await req('/api/chat','bob','POST',{message:'Shimla please',version:6});assert.equal(r.status,200);const result=await r.json();assert.equal(result.messages.length,4);assert.equal(result.messages[3].role,'assistant');assert.equal(result.preferences.destination,'Shimla');assert.equal(providerBody.contents.at(-1).role,'user');assert.equal(providerBody.contents.at(-1).parts[0].text,'Shimla please');assert.ok(providerBody.systemInstruction.parts[0].text.includes('ONE concise'));assert.equal(result.version,7);}finally{globalThis.fetch=originalFetch;delete process.env.GEMINI_API_KEY;delete process.env.GEMINI_MODEL;}});
test('API returns 429 with Retry-After and no provider call when daily cap is reached',async()=>{const oldFetch=globalThis.fetch;let calls=0;process.env.GEMINI_API_KEY='test-only';process.env.GEMINI_MODEL='test-only';const day=new Date().toISOString().slice(0,10);fixture.data.set(`aiUsageUsers/${usageUserKey('bob')}`,{day,chat:30,itinerary:0,recentChat:[]});fixture.data.set('users/bob/state/draft',{preferences:blankPreferences(),messages:[],version:20,lease:null});globalThis.fetch=async(url,options)=>{if(String(url).startsWith('https://generativelanguage.googleapis.com/')){calls++;throw Error('must not call');}return oldFetch(url,options);};try{const r=await req('/api/chat','bob','POST',{message:'Hello',version:20});assert.equal(r.status,429);assert.ok(Number(r.headers.get('Retry-After'))>0);const body=await r.json();assert.equal(body.code,'AI_CHAT_DAILY_LIMIT');assert.equal(body.operatorRequired,false);assert.ok(body.retryAt.endsWith('T00:00:00.000Z'));assert.equal(calls,0);assert.equal(fixture.data.get('users/bob/state/draft').messages.length,0);}finally{globalThis.fetch=oldFetch;delete process.env.GEMINI_API_KEY;delete process.env.GEMINI_MODEL;}});
test('kill switch and invalid limit settings do not block saved-trip reads or reviewer access',async()=>{process.env.AI_ENABLED='false';assert.equal((await req('/api/trips/'+id,'alice')).status,200);assert.equal((await req('/api/reviews','reviewer')).status,200);const config=await (await req('/api/config')).json();assert.equal(config.usageLimits.enabled,false);assert.equal(config.usageLimits.resetTimezone,'UTC');process.env.AI_CHAT_PER_DAY='bad';assert.equal((await req('/api/config')).status,503);assert.equal((await req('/api/trips/'+id,'alice')).status,200);delete process.env.AI_CHAT_PER_DAY;delete process.env.AI_ENABLED;});
