import test from 'node:test';
import assert from 'node:assert/strict';
import { z } from 'zod';
import { fakeDB } from './fake-store.js';
process.env.NODE_ENV='test';process.env.ENABLE_FIREBASE_ADMIN='true';process.env.FIREBASE_PROJECT_ID='usage-test';
const {setTestServices}=await import('../server/store.js');
const {usageConfig,reserveUsage,usageUserKey}=await import('../server/usage.js');
const {gemini}=await import('../server/ai.js');
const originalFetch=globalThis.fetch,id='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',uid='alice';
const schema=z.object({answer:z.string()}).strict(),input=[{role:'user',parts:[{text:'A fictional trip'}]}],now=Date.parse('2026-10-08T12:00:00Z');
function setup(seed={}){const fixture=fakeDB(seed);setTestServices({db:fixture.db,auth:{}});return fixture;}
const tripSeed=()=>({[`trips/${id}`]:{id,owner:uid},[`privateReviews/${id}`]:{tripId:id,owner:uid}});
function configured(){process.env.GEMINI_API_KEY='test-only';process.env.GEMINI_MODEL='test-only';}
test.beforeEach(()=>{for(const key of Object.keys(process.env))if(key.startsWith('AI_')||key==='GEMINI_API_KEY'||key==='GEMINI_MODEL')delete process.env[key];globalThis.fetch=originalFetch;});
test.after(()=>{globalThis.fetch=originalFetch;});
test('concurrent user reservations grant exactly five rolling-minute attempts',async()=>{const f=setup(),config=usageConfig({});const results=await Promise.allSettled(Array.from({length:20},()=>reserveUsage({uid,action:'chat'},config,now)));assert.equal(results.filter(r=>r.status==='fulfilled').length,5);assert.equal(f.data.get('aiUsageDays/2026-10-08').attempts,5);assert.equal(f.data.get(`aiUsageUsers/${usageUserKey(uid)}`).chat,5);assert.ok(results.filter(r=>r.status==='rejected').every(r=>r.reason.code==='AI_CHAT_RATE_LIMIT'));});
test('global transaction cap survives concurrent callers and re-created service handles',async()=>{const f=setup(),config=usageConfig({AI_GLOBAL_PER_DAY:'7'});const results=await Promise.allSettled(Array.from({length:20},(_,i)=>reserveUsage({uid:`user-${i}`,action:i%2?'chat':'itinerary'},config,now)));assert.equal(results.filter(r=>r.status==='fulfilled').length,7);setTestServices({db:f.db,auth:{}});await assert.rejects(()=>reserveUsage({uid:'another',action:'chat'},config,now+1000),e=>e.code==='AI_GLOBAL_DAILY_LIMIT');assert.equal(f.data.get('aiUsageDays/2026-10-08').attempts,7);});
test('one global budget spans chat, itinerary and explanation actions',async()=>{const f=setup(tripSeed()),config=usageConfig({AI_GLOBAL_PER_DAY:'3'});for(const action of ['chat','itinerary','explanation'])await reserveUsage({uid,action,...(action==='explanation'?{tripId:id}:{})},config,now);await assert.rejects(()=>reserveUsage({uid:'other',action:'chat'},config,now),e=>e.code==='AI_GLOBAL_DAILY_LIMIT');assert.equal(f.data.get('aiUsageDays/2026-10-08').attempts,3);});
test('daily chat/itinerary caps are per user and cannot be bypassed by resetting drafts',async()=>{const f=setup(),config=usageConfig({AI_CHAT_PER_DAY:'2',AI_ITINERARIES_PER_DAY:'1'});await reserveUsage({uid,action:'chat'},config,now);await reserveUsage({uid,action:'chat'},config,now+61000);f.data.delete(`users/${uid}/state/draft`);await assert.rejects(()=>reserveUsage({uid,action:'chat'},config,now+122000),e=>e.code==='AI_CHAT_DAILY_LIMIT');await reserveUsage({uid,action:'itinerary'},config,now);await assert.rejects(()=>reserveUsage({uid,action:'itinerary'},config,now),e=>e.code==='AI_ITINERARY_DAILY_LIMIT');await reserveUsage({uid:'bob',action:'itinerary'},config,now);});
test('UTC daily rollover resets daily counts but preserves the rolling-minute window',async()=>{const f=setup(),config=usageConfig({AI_CHAT_PER_MINUTE:'1',AI_CHAT_PER_DAY:'1',AI_GLOBAL_PER_DAY:'1'}),before=Date.parse('2026-10-08T23:59:50Z');await reserveUsage({uid,action:'chat'},config,before);await assert.rejects(()=>reserveUsage({uid,action:'chat'},config,before+20000),e=>e.code==='AI_CHAT_RATE_LIMIT'&&e.retryAt==='2026-10-09T00:00:50.000Z');await reserveUsage({uid,action:'chat'},config,before+60000);assert.equal(f.data.get('aiUsageDays/2026-10-09').attempts,1);assert.equal(f.data.get(`aiUsageUsers/${usageUserKey(uid)}`).chat,1);});
test('explanation attempt cap belongs to immutable trip and does not reset at midnight',async()=>{const f=setup(tripSeed()),config=usageConfig({});await reserveUsage({uid,action:'explanation',tripId:id},config,now);await reserveUsage({uid,action:'explanation',tripId:id},config,now+86400000);await assert.rejects(()=>reserveUsage({uid,action:'explanation',tripId:id},config,now+2*86400000),e=>e.code==='AI_EXPLANATION_EXHAUSTED'&&e.operatorRequired&&e.retryAt===null);assert.equal(f.data.get(`aiExplanationUsage/${id}`).attempts,2);assert.equal(f.data.has('aiUsageDays/2026-10-10'),false);});
test('failed provider attempts consume quotas and are never refunded or auto-retried',async()=>{const f=setup();configured();let calls=0;globalThis.fetch=async()=>{calls++;throw Error('network failure');};for(let i=0;i<5;i++)await assert.rejects(()=>gemini({uid,action:'chat'},'Trusted instruction',input,schema),e=>e.status===502);await assert.rejects(()=>gemini({uid,action:'chat'},'Trusted instruction',input,schema),e=>e.status===429);assert.equal(calls,5);assert.equal(f.data.get(`aiUsageUsers/${usageUserKey(uid)}`).chat,5);});
test('invalid config, missing credentials, kill switch and zero limits consume no quota',async()=>{const f=setup();let calls=0;globalThis.fetch=async()=>{calls++;throw Error('should not call');};await assert.rejects(()=>gemini({uid,action:'chat'},'Trusted',input,schema),e=>e.code==='AI_UNCONFIGURED');configured();for(const [name,value,code] of [['AI_CHAT_PER_DAY','oops','AI_CONFIG_INVALID'],['AI_ENABLED','false','AI_DISABLED'],['AI_CHAT_PER_MINUTE','0','AI_ACTION_DISABLED'],['AI_CHAT_MAX_OUTPUT_TOKENS','0','AI_ACTION_DISABLED'],['AI_MAX_INPUT_CHARS','0','AI_ACTION_DISABLED']]){process.env[name]=value;await assert.rejects(()=>gemini({uid,action:'chat'},'Trusted',input,schema),e=>e.code===code);delete process.env[name];}assert.equal(calls,0);assert.equal(f.data.size,0);});
test('invalid, oversized or context-free input consumes no quota',async()=>{const f=setup();configured();globalThis.fetch=async()=>{throw Error('must not reach provider');};await assert.rejects(()=>gemini(null,'Trusted',input,schema),e=>e.code==='AI_CONTEXT_INVALID');await assert.rejects(()=>gemini({uid,action:'chat'},'Trusted',[{role:'system',parts:[{text:'forged'}]}],schema),e=>e.status===422);process.env.AI_MAX_INPUT_CHARS='100';await assert.rejects(()=>gemini({uid,action:'chat'},'Trusted',input,schema),e=>e.status===413);assert.equal(f.data.size,0);});
test('storage failures and corrupt counters fail closed before provider access',async()=>{configured();let calls=0;globalThis.fetch=async()=>{calls++;throw Error('must not call');};setTestServices({db:{runTransaction:async()=>{throw Error('offline');},doc:path=>({path})},auth:{}});await assert.rejects(()=>gemini({uid,action:'chat'},'Trusted',input,schema),e=>e.code==='AI_USAGE_UNAVAILABLE');const day=new Date().toISOString().slice(0,10);setup({[`aiUsageDays/${day}`]:{day,attempts:-1}});await assert.rejects(()=>gemini({uid,action:'chat'},'Trusted',input,schema),e=>e.code==='AI_USAGE_UNAVAILABLE');assert.equal(calls,0);});
test('successful explanation draft is reused even when attempt/global limits are spent',async()=>{const day=new Date().toISOString().slice(0,10),seed=tripSeed();seed[`privateReviews/${id}`].draft='This cached explanation remains private pending human review.';seed[`aiExplanationUsage/${id}`]={ownerHash:usageUserKey(uid),attempts:2};seed[`aiUsageDays/${day}`]={day,attempts:200};const f=setup(seed);configured();let calls=0;globalThis.fetch=async()=>{calls++;throw Error('must not call');};const result=await gemini({uid,action:'explanation',tripId:id},'Trusted',input,z.object({explanation:z.string()}));assert.equal(result.explanation,seed[`privateReviews/${id}`].draft);assert.equal(calls,0);assert.equal(f.data.get(`aiUsageDays/${day}`).attempts,200);});
test('provider receives configured output cap; reservation exists before fetch',async()=>{const f=setup();configured();process.env.AI_ITINERARY_MAX_OUTPUT_TOKENS='1234';let body;globalThis.fetch=async(url,options)=>{body=JSON.parse(options.body);assert.equal(f.data.get(`aiUsageUsers/${usageUserKey(uid)}`).itinerary,1);return new Response(JSON.stringify({candidates:[{content:{parts:[{text:'{"answer":"ok"}'}]}}]}),{status:200});};const result=await gemini({uid,action:'itinerary'},'Trusted',input,schema);assert.equal(result.answer,'ok');assert.equal(body.generationConfig.maxOutputTokens,1234);});
test('transaction test double rolls back all staged writes on failure',async()=>{const f=setup({counter:{n:0}});await assert.rejects(()=>f.db.runTransaction(async tx=>{tx.update(f.db.doc('counter'),{n:1});tx.create(f.db.doc('counter'),{n:2});}));assert.equal(f.data.get('counter').n,0);});
