import { randomUUID,timingSafeEqual } from 'node:crypto';
import { services,assertActive } from './store.js';
import { explain } from './ai.js';
import { Problem,resolvePersona } from './domain.js';
import {UsageProblem} from './usage.js';
export const automationReady=()=>process.env.ENABLE_AUTOMATION==='true'&&(process.env.AUTOMATION_TOKEN||'').length>=32&&Boolean(process.env.AIRTABLE_TOKEN);
export function serviceAuth(req,res,next){const actual=Buffer.from(req.headers.authorization||''),expected=Buffer.from(`Bearer ${process.env.AUTOMATION_TOKEN||''}`);if(!automationReady()||actual.length!==expected.length||!timingSafeEqual(actual,expected))return res.status(401).json({error:'Automation authentication required.'});next();}
const base=()=>process.env.AIRTABLE_BASE_ID||'appV8g3WvLNKVEPom';
async function airtable(path,method='GET',body){const response=await fetch(`https://api.airtable.com/v0/${path}`,{method,signal:AbortSignal.timeout(20000),headers:{Authorization:`Bearer ${process.env.AIRTABLE_TOKEN}`,'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});if(!response.ok)throw new Problem(502,`Airtable returned ${response.status}. Check the integration configuration.`);return response.status===204?{}:response.json();}
async function records(table){let result=[],offset;do{const data=await airtable(`${base()}/${encodeURIComponent(table)}?pageSize=100${offset?`&offset=${encodeURIComponent(offset)}`:''}`);result.push(...data.records);offset=data.offset;}while(offset);return result;}
async function verifySchema(){const meta=await airtable(`meta/bases/${base()}/tables`),personas=meta.tables.find(t=>t.name==='Personas'),log=meta.tables.find(t=>t.name==='Itinerary_Log');if(!personas||!log)throw new Problem(409,'Personas and Itinerary_Log must already exist.');const link=log.fields.find(f=>f.name==='Persona');if(link?.type!=='multipleRecordLinks'||link.options?.linkedTableId!==personas.id)throw new Problem(409,'Persona must be a real Linked Record to Personas.');for(const field of ['Timestamp','Itinerary Summary','AI Explanation','Review Status'])if(!log.fields.some(f=>f.name===field))throw new Problem(409,`Missing Airtable field: ${field}.`);}
const marker=id=>`Evaluation trip ${id}`;
async function reconcile(id){const matches=(await records('Itinerary_Log')).filter(r=>String(r.fields['Itinerary Summary']||'').startsWith(marker(id)+';'));if(matches.length>1)throw new Problem(409,'Duplicate external rows require human reconciliation.');return matches[0];}
export async function pendingEvents(now=Date.now()){
 const rows=await services().db.collection('automationEvents').where('status','in',['queued','failed']).get();
 return rows.docs.filter(d=>{const event=d.data();return !event.operatorRequired&&(!event.retryAt||Number.isFinite(Date.parse(event.retryAt))&&Date.parse(event.retryAt)<=now);}).slice(0,25).map(d=>({tripId:d.id,retryAt:d.data().retryAt||null}));
}
export function automationAttemptLimit(){const raw=process.env.AUTOMATION_MAX_ATTEMPTS??'5';if(!/^[1-9]\d*$/.test(raw)||Number(raw)>20)throw new UsageProblem('Automation attempt limits are not configured correctly.',{code:'AUTOMATION_CONFIG_INVALID',status:503,operatorRequired:true});return Number(raw);}
export async function processEvent(id){
 if(!automationReady())throw new Problem(503,'Automation is not configured.');const maxProcessingAttempts=automationAttemptLimit();
 const {db}=services(),eventRef=db.doc(`automationEvents/${id}`),jobRef=db.doc(`privateReviews/${id}`),token=randomUUID();
 const claim=await db.runTransaction(async tx=>{const ev=await tx.get(eventRef);if(!ev.exists)throw new Problem(404,'Event not found.');const tripSnap=await tx.get(db.doc(`trips/${id}`));if(!tripSnap.exists)throw new Problem(404,'Trip not found.');const trip=tripSnap.data();await assertActive(tx,trip.owner);const job=(await tx.get(jobRef)).data();const event=ev.data();if(event.operatorRequired||event.status==='blocked'||job?.status==='Blocked')throw new UsageProblem('This automation needs operator attention before retrying.',{code:event.code||'AI_OPERATOR_REQUIRED',operatorRequired:true});if(event.retryAt&&Date.parse(event.retryAt)>Date.now())throw new UsageProblem('This automation is waiting before retrying.',{code:event.code||'AI_RETRY_WAIT',retryAt:event.retryAt});if(job?.status==='Pending'||job?.status==='Approved'||job?.status==='Rejected')return {done:true};if(job?.leaseUntil>Date.now())throw new Problem(409,'Automation is already running.');const attempts=job?.processingAttempts??0;if(!Number.isSafeInteger(attempts)||attempts<0)throw new UsageProblem('Automation attempt history is invalid.',{code:'AUTOMATION_STATE_INVALID',status:503,operatorRequired:true});if(attempts>=maxProcessingAttempts){tx.set(jobRef,{...(job||{}),owner:trip.owner,tripId:id,status:'Blocked',operatorRequired:true,retryAt:null},{merge:true});tx.update(eventRef,{status:'blocked',operatorRequired:true,retryAt:null,code:'AUTOMATION_ATTEMPTS_EXHAUSTED'});return {blocked:true};}tx.set(jobRef,{...(job||{}),owner:trip.owner,tripId:id,status:'Processing',processingAttempts:attempts+1,leaseToken:token,leaseUntil:Date.now()+180000},{merge:true});tx.update(eventRef,{status:'processing',retryAt:null});return {trip,job:{...(job||{}),processingAttempts:attempts+1}};});
 if(claim.done)return {status:'Already processed'};if(claim.blocked)throw new UsageProblem('This automation has exhausted its processing attempts. An operator must review it.',{code:'AUTOMATION_ATTEMPTS_EXHAUSTED',operatorRequired:true});
 try{
  await verifySchema();
  let job=claim.job;
  if(!job.draft){const generated=await explain(claim.trip);await db.runTransaction(async tx=>{const current=(await tx.get(jobRef)).data();if(current?.leaseToken!==token)throw new Problem(409,'Automation lease changed.');tx.update(jobRef,{draft:generated.explanation});});job={...job,draft:generated.explanation};}
  const personaId=resolvePersona(await records('Personas'),claim.trip.preferences.persona);
  let row=job.airtableId?{id:job.airtableId}:await reconcile(id);
  if(!row&&job.writeAttempted)throw new Problem(409,'An earlier Airtable write has an unknown outcome. Inspect Airtable and reconcile before another create.');
  if(!row){await jobRef.update({writeAttempted:true});const p=claim.trip.preferences;const created=await airtable(`${base()}/Itinerary_Log`,'POST',{records:[{fields:{Timestamp:claim.trip.createdAt,Persona:[personaId],'Itinerary Summary':`${marker(id)}; fictional/de-identified ${p.travellerType} evaluation; ${claim.trip.plan.days.length} days; ${p.adults+p.elders+p.children} travellers; coverage ${claim.trip.plan.coverage}; costs unknown.`,'AI Explanation':'','Review Status':'Pending'}}],typecast:false});row=created.records[0];}
  await db.runTransaction(async tx=>{const latest=(await tx.get(jobRef)).data();if(latest.leaseToken!==token)throw new Problem(409,'Automation lease changed.');tx.update(jobRef,{airtableId:row.id,status:'Pending',leaseUntil:0,error:null});tx.update(eventRef,{status:'awaiting-review',retryAt:null,operatorRequired:false});tx.update(db.doc(`trips/${id}`),{reviewStatus:'Pending'});});return {status:'Awaiting human review'};
 }catch(error){await db.runTransaction(async tx=>{const current=(await tx.get(jobRef)).data();if(current?.leaseToken===token){const processingExhausted=claim.job.processingAttempts>=maxProcessingAttempts,operatorRequired=Boolean(error.operatorRequired)||processingExhausted,retryAt=operatorRequired?null:error.retryAt||new Date(Date.now()+60000).toISOString(),message=error instanceof Problem?error.message:'Provider operation failed. Inspect integration status before retrying.';tx.update(jobRef,{status:operatorRequired?'Blocked':'Failed',leaseUntil:0,error:message,retryAt,operatorRequired});tx.update(eventRef,{status:operatorRequired?'blocked':'failed',retryAt,operatorRequired,code:processingExhausted?'AUTOMATION_ATTEMPTS_EXHAUSTED':error.code||'AUTOMATION_FAILED',error:message});tx.update(db.doc(`trips/${id}`),{reviewStatus:operatorRequired?'Needs operator':'Retry scheduled'});}});if(claim.job.processingAttempts>=maxProcessingAttempts){error.operatorRequired=true;error.retryAt=null;error.code='AUTOMATION_ATTEMPTS_EXHAUSTED';}else if(!error.operatorRequired){error.retryAt=error.retryAt||new Date(Date.now()+60000).toISOString();error.code=error.code||'AUTOMATION_FAILED';}throw error;}
}
export async function review(id,decision,text,reviewer){
 const {db}=services(),ref=db.doc(`privateReviews/${id}`),token=randomUUID();
 const job=await db.runTransaction(async tx=>{const s=await tx.get(ref);if(!s.exists)throw new Problem(404,'Review not found.');const j=s.data();await assertActive(tx,j.owner);if(j.status==='Approved'||j.status==='Rejected')throw new Problem(409,'This review already has a final decision.');if(!j.airtableId||!['Pending','Sync failed'].includes(j.status)||j.leaseUntil>Date.now())throw new Problem(409,'This item is not ready for review.');if(j.decision&&j.decision!==decision)throw new Problem(409,'Resume the original review decision to reconcile its external write.');const approvedText=j.approvedText||(decision==='Approved'?text:'');tx.update(ref,{status:'Syncing',decision,approvedText,reviewedBy:reviewer,leaseToken:token,leaseUntil:Date.now()+90000});return {...j,approvedText};});
 try{await airtable(`${base()}/Itinerary_Log/${job.airtableId}`,'PATCH',{fields:{'AI Explanation':decision==='Approved'?job.approvedText:'','Review Status':decision}});const confirmed=await airtable(`${base()}/Itinerary_Log/${job.airtableId}`);if((confirmed.fields['AI Explanation']||'')!==(decision==='Approved'?job.approvedText:'')||confirmed.fields['Review Status']!==decision)throw new Problem(502,'Airtable read-back did not confirm the review.');
 await db.runTransaction(async tx=>{const current=(await tx.get(ref)).data();if(current.leaseToken!==token)throw new Problem(409,'Review lease changed.');tx.update(ref,{status:decision,leaseUntil:0,reviewedAt:new Date().toISOString()});tx.update(db.doc(`trips/${id}`),{reviewStatus:decision,approvedExplanation:decision==='Approved'?job.approvedText:null});tx.update(db.doc(`automationEvents/${id}`),{status:'complete'});});return {status:decision};
 }catch(error){await db.runTransaction(async tx=>{const current=(await tx.get(ref)).data();if(current?.leaseToken===token)tx.update(ref,{status:'Sync failed',leaseUntil:0});});throw error;}
}
export async function deleteExternal(rowId){if(!automationReady())throw new Problem(503,'Reconnect Airtable before deleting linked records.');await airtable(`${base()}/Itinerary_Log/${rowId}`,'DELETE');}
export async function dispatch(id){if(!automationReady()||!process.env.N8N_WEBHOOK_URL)return;const url=new URL(process.env.N8N_WEBHOOK_URL);if(url.protocol!=='https:'&&url.hostname!=='localhost'&&url.hostname!=='127.0.0.1')throw new Problem(503,'Workflow endpoint must use HTTPS.');try{const r=await fetch(url,{method:'POST',signal:AbortSignal.timeout(10000),headers:{'Content-Type':'application/json',Authorization:`Bearer ${process.env.AUTOMATION_TOKEN}`},body:JSON.stringify({tripId:id})});if(!r.ok)throw Error();}catch{await services().db.doc(`automationEvents/${id}`).update({dispatchError:'Workflow delivery failed; event remains available for retry.'});}}

